# Copyright (C) 2022 Andrew Rioux
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: standard-dev
requires:
  - configs:
    - host-configuration-dev
    path: Services/HostConfiguration/skaffold.yml
  - configs:
    - base-api-dev
    path: Apis/Main/skaffold.yml
  - configs:
    - admin-static-dev
    - main-static-dev
    path: Client/skaffold.yml

---

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: authentication-dev
requires:
  - configs:
    - host-configuration-dev
    path: Services/HostConfiguration/skaffold.yml
  - configs:
    - base-api-dev
    path: Apis/Main/skaffold.yml
  - configs:
    - admin-static-dev
    - main-static-dev
    path: Client/skaffold.yml
  - configs:
    - authentication-dev
    path: Services/Authentication/skaffold.yml


---

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: capwatch-dev
requires:
  - configs:
    - host-configuration-dev
    path: Services/HostConfiguration/skaffold.yml
  - configs:
    - base-api-dev
    path: Apis/Main/skaffold.yml
  - configs:
    - admin-static-dev
    - main-static-dev
    path: Client/skaffold.yml
  - configs:
    - capwatch-dev
    path: Services/Capwatch/skaffold.yml


---

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: files-dev
requires:
  - configs:
    - host-configuration-dev
    path: Services/HostConfiguration/skaffold.yml
  - configs:
    - base-api-dev
    path: Apis/Main/skaffold.yml
  - configs:
    - admin-static-dev
    - main-static-dev
    path: Client/skaffold.yml
  - configs:
    - files-dev
    path: Services/Files/skaffold.yml


---

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: graph-dev
requires:
  - configs:
    - host-configuration-dev
    path: Services/HostConfiguration/skaffold.yml
  - configs:
    - base-api-dev
    path: Apis/Main/skaffold.yml
  - configs:
    - admin-static-dev
    - main-static-dev
    path: Client/skaffold.yml
  - configs:
    - graph-dev
    path: Services/Graph/skaffold.yml

---

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: production
requires:
  - configs:
    - host-configuration
    path: Services/HostConfiguration/skaffold.yml
  - configs:
    - base-api
    path: Apis/Main/skaffold.yml
  - configs:
    - admin-static
    - main-static
    path: Client/skaffold.yml
  - configs:
    - authentication
    path: Services/Authentication/skaffold.yml
  - configs:
    - capwatch
    path: Services/Capwatch/skaffold.yml
  - configs:
    - files
    path: Services/Files/skaffold.yml
  - configs:
    - graph
    path: Services/Graph/skaffold.yml