# Copyright (C) 2022 Andrew Rioux
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: unitplannerv7
  name: host-configuration-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: unitplannerv7
  name: manage-ingresses
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs:
      - create
      - patch
      - replace
      - delete
      - get
      - list
      - read

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: unitplannerv7
  name: host-configuration-ingress-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-ingresses
subjects:
  - kind: ServiceAccount
    name: host-configuration-service-account
    namespace: unitplannerv7

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: unitplannerv7
  name: host-configuration
spec:
  selector:
    matchLabels:
      name: host-configuration
  template:
    metadata:
      labels:
        name: host-configuration
    spec:
      containers:
      - name: host-configuration
        image: ghcr.io/cap-md089/unitplannerv7/services/hostconfiguration
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5050
      serviceAccountName: host-configuration-service-account
