# Copyright (C) 2022 Andrew Rioux
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: capwatch-dev
build:
  artifacts:
  - image: ghcr.io/cap-md089/unitplannerv7/services/capwatch
    docker:
      dockerfile: Services/Capwatch/Dockerfile
      target: dev
    context: ../..
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - ../../k8s/service-capwatch.yaml

---

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: capwatch
build:
  artifacts:
  - image: ghcr.io/cap-md089/unitplannerv7/services/capwatch
    docker:
      dockerfile: Services/Capwatch/Dockerfile
      target: final
    context: ../..
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - ../../k8s/service-capwatch.yaml