# build-and-test.yaml: Describes the GitHub action that
#
# Copyright (C) 2021 Andrew Rioux
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Integration tests

on:
  pull_request:
    branches:
      - master

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: manusa/actions-setup-minikube@v2.4.3
        with:
          kubernetes version: 'v1.23.3'
          minikube version: 'v1.25.2'
        
      - name: Install skaffold
        run: |
          sudo curl -Lo /usr/bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo chmod +x /usr/bin/skaffold

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          build: /home/runner/work/UnitPlannerv7/UnitPlannerv7/scripts/gha-build-test-env.sh
          start: /home/runner/work/UnitPlannerv7/UnitPlannerv7/scripts/gha-start-test-env.sh
          spec: cypress/integration/**/*.spec.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
